import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Download, FileText } from "lucide-react";
import { toast } from "sonner";

interface LeadResultsTableProps {
  htmlContent: string;
}

const AVAILABLE_COLUMNS = [
  "Business Name",
  "Address",
  "City",
  "Country",
  "Website",
  "Phone Raw",
  "Google Maps URL",
  "Reviews Count",
  "Ads",
  "Rank",
];

export const LeadResultsTable = ({ htmlContent }: LeadResultsTableProps) => {
  const [visibleColumns, setVisibleColumns] = useState<string[]>(AVAILABLE_COLUMNS);
  const [tableData, setTableData] = useState<any[]>([]);

  useEffect(() => {
    // Parse HTML content to extract table data
    const parser = new DOMParser();
    const doc = parser.parseFromString(htmlContent, "text/html");
    const rows = doc.querySelectorAll("table tr");
    
    const data: any[] = [];
    rows.forEach((row, index) => {
      if (index === 0) return; // Skip header
      const cells = row.querySelectorAll("td");
      if (cells.length > 0) {
        data.push({
          "Business Name": cells[0]?.textContent || "",
          "Address": cells[1]?.textContent || "",
          "City": cells[2]?.textContent || "",
          "Country": cells[3]?.textContent || "",
          "Website": cells[4]?.textContent || "",
          "Phone Raw": cells[5]?.textContent || "",
          "Google Maps URL": cells[6]?.textContent || "",
          "Reviews Count": cells[7]?.textContent || "",
          "Ads": cells[8]?.textContent || "",
          "Rank": cells[9]?.textContent || "",
        });
      }
    });
    setTableData(data);
  }, [htmlContent]);

  const toggleColumn = (column: string) => {
    setVisibleColumns((prev) =>
      prev.includes(column)
        ? prev.filter((c) => c !== column)
        : [...prev, column]
    );
  };

  const exportToHTML = () => {
    const filteredHtml = generateFilteredHTML();
    const blob = new Blob([filteredHtml], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `leads-${new Date().toISOString().split("T")[0]}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("HTML file downloaded!");
  };

  const exportToPDF = async () => {
    try {
      // Using html2pdf.js would require installing it
      // For now, we'll use the browser's print function
      const filteredHtml = generateFilteredHTML();
      const printWindow = window.open("", "_blank");
      if (printWindow) {
        printWindow.document.write(filteredHtml);
        printWindow.document.close();
        printWindow.onload = () => {
          printWindow.print();
          toast.success("Opening print dialog...");
        };
      }
    } catch (error) {
      toast.error("Failed to generate PDF");
    }
  };

  const generateFilteredHTML = () => {
    const date = new Date().toLocaleDateString();
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Google Maps Lead Extractor Results</title>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; padding: 40px; }
    h1 { color: #1e40af; margin-bottom: 10px; }
    .date { color: #666; margin-bottom: 30px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
    th { background: #3b82f6; color: white; padding: 12px; text-align: left; font-weight: 600; }
    td { padding: 12px; border-bottom: 1px solid #e5e7eb; }
    tr:nth-child(even) { background: #f9fafb; }
    tr:hover { background: #f3f4f6; }
    .footer { text-align: center; color: #666; margin-top: 40px; padding-top: 20px; border-top: 2px solid #e5e7eb; }
  </style>
</head>
<body>
  <h1>GOOGLE MAPS LEAD EXTRACTOR</h1>
  <div class="date">Generated on ${date}</div>
  <table>
    <thead>
      <tr>
        ${visibleColumns.map((col) => `<th>${col}</th>`).join("")}
      </tr>
    </thead>
    <tbody>
      ${tableData
        .map(
          (row) => `
        <tr>
          ${visibleColumns.map((col) => `<td>${row[col] || ""}</td>`).join("")}
        </tr>
      `
        )
        .join("")}
    </tbody>
  </table>
  <div class="footer">
    Generated by Google Maps Lead Extractor - ${date}
  </div>
</body>
</html>`;
  };

  return (
    <div className="space-y-6">
      {/* Column Toggles */}
      <div className="bg-card rounded-lg border p-4">
        <h3 className="font-semibold mb-3">Visible Columns</h3>
        <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
          {AVAILABLE_COLUMNS.map((column) => (
            <div key={column} className="flex items-center space-x-2">
              <Checkbox
                id={column}
                checked={visibleColumns.includes(column)}
                onCheckedChange={() => toggleColumn(column)}
              />
              <label
                htmlFor={column}
                className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer"
              >
                {column}
              </label>
            </div>
          ))}
        </div>
      </div>

      {/* Export Buttons */}
      <div className="flex gap-3">
        <Button onClick={exportToHTML} variant="outline">
          <FileText className="mr-2 h-4 w-4" />
          Download HTML
        </Button>
        <Button onClick={exportToPDF}>
          <Download className="mr-2 h-4 w-4" />
          Download PDF
        </Button>
      </div>

      {/* Results Table */}
      <div className="rounded-lg border bg-card overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b bg-muted/50">
                {visibleColumns.map((column) => (
                  <th
                    key={column}
                    className="px-4 py-3 text-left text-sm font-semibold"
                  >
                    {column}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {tableData.length === 0 ? (
                <tr>
                  <td
                    colSpan={visibleColumns.length}
                    className="px-4 py-8 text-center text-muted-foreground"
                  >
                    No leads found
                  </td>
                </tr>
              ) : (
                tableData.map((row, index) => (
                  <tr
                    key={index}
                    className="border-b hover:bg-muted/30 transition-colors"
                  >
                    {visibleColumns.map((column) => (
                      <td key={column} className="px-4 py-3 text-sm">
                        {column === "Website" || column === "Google Maps URL" ? (
                          row[column] ? (
                            <a
                              href={row[column]}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="text-primary hover:underline"
                            >
                              {row[column].length > 30
                                ? row[column].substring(0, 30) + "..."
                                : row[column]}
                            </a>
                          ) : (
                            "-"
                          )
                        ) : (
                          row[column] || "-"
                        )}
                      </td>
                    ))}
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      <div className="text-center text-sm text-muted-foreground pt-4">
        Generated by Google Maps Lead Extractor - {new Date().toLocaleDateString()}
      </div>
    </div>
  );
};
